Fix/ci
divio/djangocms-versioning-filer pull request #95
Opened 2022-09-07 15:57 UTC by michaeljcollinsuk

Replaces CircleCI with Github Actions. The decision to change was made due to errors related to a missing $CIRCLE_STAGE environment variable. There has also been a general move away from Circle CI to Git Hub actions in our other packages, such as [djangocms-navigation](https://github.com/FidelityInternational/djangocms-navigation/commit/facc70270d9224e199278afb64b58a70e0bb43da).

This also fixes the `test_migrations` test that was resulting in a fail due to a missing migration when testing with django 3.2, which uses `BigAutoField` as the default for a PK. Previously the test would also check for missing migrations in its dependencies, which are out of our control. So the test has been limited to check for missing migrations in the `djangocms_versioning_filer` app only.

Finally it updates the test requirements to use the latest version of django-filer, and updates tests accordingly to resolve errors from the upgrede.

2022-10-06 15:20 UTC, adam-murray commented on test_settings.py
> +    'CMS_CONFIRM_VERSION4': True,
Could we move the djangocms version to use a stable release channel?

2022-10-13 09:23 UTC, adam-murray approved these changes

2022-10-13 09:26 UTC, Bernardvdv requested changes
Changelog entry required

2022-10-13 09:30 UTC, Bernardvdv approved these changes

2022-10-13 09:33 UTC, merged